xgb:
  estimator_class_name: XGBClassifier
  estimator_module: xgboost.sklearn
  params:
    xgb__base_score: 0.5
    xgb__booster: gbtree
    xgb__colsample_bylevel: !!python/object/apply:numpy.core.multiarray.scalar
    - &id001 !!python/object/apply:numpy.dtype
      args:
      - f8
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - -1
      - -1
      - 0
    - !!binary |
      8IfGZm4czD8=
    xgb__colsample_bynode: !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      AKpI15RZsj8=
    xgb__colsample_bytree: !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      4A05OYzl5z8=
    xgb__eta: !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      MhZhULUi0z8=
    xgb__eval_metric: auc
    xgb__gamma: !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      +s0TXE0fFkA=
    xgb__gpu_id: -1
    xgb__importance_type: gain
    xgb__interaction_constraints: ''
    xgb__learning_rate: 0.298993438
    xgb__max_delta_step: !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      T626SeSEF0A=
    xgb__max_depth: 5
    xgb__min_child_weight: !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      jytiQFTJN0A=
    xgb__missing: .nan
    xgb__monotone_constraints: ()
    xgb__n_estimators: 100
    xgb__n_jobs: 32
    xgb__num_parallel_tree: 4
    xgb__objective: binary:logistic
    xgb__random_state: 0
    xgb__reg_alpha: 0
    xgb__reg_lambda: 1
    xgb__sampling_method: gradient_based
    xgb__scale_pos_weight: !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      wvFETdm7IUA=
    xgb__subsample: 1
    xgb__tree_method: exact
    xgb__use_label_encoder: false
    xgb__validate_parameters: 1
    xgb__verbosity: null
