covid_names:
  - covid
  - covid-19
  - coronavirus
  - sars-cov-2
  - ncov2
covid_level_names:
  Level 0 (Direct C19 actions): l0_direct_actions
  Level 1 (Health Emergency Fighting): l1_health_emergency
  Level 2 (Resilience and Preparedness): l2_resilience
model_parametres:
    - estimator__C: [0.5, 1, 2]
      estimator__class_weight: ["balanced"]
      estimator__penalty: ["l2", "l1"]
    - estimator__class_weight: ["balanced"]
      estimator__min_samples_leaf: [2, 5]
      estimator__n_estimators: [20, 50, 100]
fetch_columns:
  nih_projects:
    - application_id
    - ic_name
    - org_country
    - project_start
    - project_title
    - total_cost
  gtr_projects:
    - id
    - title
    - status
    - abstractText
    - start
finding_ai:
  min_count: 700
  topic_filter:
    presence_threshold: 0
    prevalence_threshold: 0.1
  expansion_dict:
    cs.AI: 2
    cs.NE: 2
    cs.LG: 1
    stat.ML: 1