channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.8
  - numpy
  - scipy
  - scikit-learn
  - giuliorossetti
  - graph-tool
  - cdlib
  # Only put dependencies that are NOT available with pip here (e.g. graph-tool)
  # or that enable extra functionality such as GPU/MKL support
