name: Node.js CI

on:
  push:
    branches: dev
  pull_request:
    branches: dev

jobs:
  browserstack-controller:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run selenium
    - uses: popsiclestick/gist-sync-action@v1.2.0
      id: sync
      with:
        auth: ${{ secrets.BROWSERSTACK_GIST_TOKEN }}
        gist_url: https://gist.github.com/NestaTestUser/8fb890ee1ebf84435539faa7996b140e
        gist_title: Browserstack test results for Eurito Indicators webapp
        gist_description: Browserstack test results for Eurito Indicators webapp
        github_file: data/tests/selenium-report.json